name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies (photolodge-api)
      run: npm install
      working-directory: photolodge-api

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push photolodge-api
      uses: docker/build-push-action@v4
      with:
        context: ./photolodge-api
        file: ./photolodge-api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/photolodge-api:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
